name: freebox
description: "Un wrapper pour l'API de Freebox OS, gÃ¨re la connexion et facilite les requÃªtes."
version: 1.0.1
repository: https://github.com/Freebox-Tools/dart-freebox

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.5
  flutter:
    sdk: flutter
  http: ^1.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

